#!/bin/bash

WORD=$*
: "${OXFORD_APP_ID:?Set OXFORD_APP_ID}"
: "${OXFORD_APP_KEY:?Set OXFORD_APP_KEY}"

URL_BASE='https://od-api.oxforddictionaries.com:443/api/v1/entries/en/'
REGION='/regions=us'

URL=$URL_BASE$WORD$REGION


curl -s -X GET \
	--header 'Accept: application/json' \
	--header 'app_id: $OXFORD_APP_ID' \
	--header 'app_key: $OXFORD_APP_KEY' \
	$URL > ~/.scripts/define.json

jq '.results[0].lexicalEntries[0].entries[0].senses[0].definitions[0]' ~/.scripts/define.json > ~/.scripts/define.txt

echo "#var definition {" > ~/.scripts/def.tin
cat ~/.scripts/define.txt >> ~/.scripts/def.tin
echo "}" >> ~/.scripts/def.tin
