#!/bin/bash
SCREENID=$(tmux list-sessions | grep $1)
if (( ${#SCREENID} > 0 ));
then
	SCREENID=$1
	tmux attach-session -t $1
else
	tmux start-server
	tmux new-session -d -s $1 -n TT
	tmux split-window -v
	tmux select-pane -t 0
	tmux split-window -h
	tmux resize-pane -x 45 -y 18
	tmux select-pane -t 2
	tmux send-keys -t $1.0 "tail -f .tt/logs/$1.chat" C-m
	tmux send-keys -t $1.1 "watch -t -c -n 0.1 cat .tt/map/map.txt" C-m
	tmux send-keys -t $1.2 "tt" C-m
	tmux attach-session -t $1
fi
unset SCREENID
