#!/bin/bash


URL_BASE='https://aviationweather.gov/adds/dataserver_current/httpparam?datasource=metars&requesttype=retrieve&format=csv&hoursBeforeNow=5&mostRecentForEachStation=true&stationString='
TAF_BASE='https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=tafs&requestType=retrieve&format=csv&hoursBeforeNow=30&mostRecentForEachStation=true&stationString='

INPUT=adds.csv

FIELDS=$*

for i in $(echo $FIELDS | sed "s/,/ /g")
do
	URL=$URL_BASE$i
	TAF_URL=$TAF_BASE$i

	curl -s $URL >> adds.csv
	curl -s $TAF_URL >> adds.csv
done

echo "-------------------------------------------------------------------------"


if [ -s $INPUT ]
  then
	RAW_READ="FALSE"
	DATA="blank"
	DATA_SOURCE="none"
	FIRST_METAR="true"
	while read line
	do
		DATA=${line%%,*}
		if [ $RAW_READ = "TRUE" ]
		  then
			if [[ $DATA == "No errors" ]]
			  then
				RAW_READ="FALSE"
			else
				if [[ $DATA_SOURCE == "metars" ]]
				  then
					if [[ $FIRST_METAR == "true" ]]
					 then
						FIRST_METAR="false"
					else
						echo
					fi
					echo $DATA
				elif [[ $DATA_SOURCE == "tafs" ]]
				  then
					TAF=$(echo $DATA | sed -e "s/\(BECMG\|TEMPO\|PROB\|FM\)/\n&/g")
					echo "$TAF"
				fi
			fi
		elif [[ ${DATA:0:11} == "data source" ]]
		  then
			DATA_SOURCE=${DATA:12}
		elif [[ $DATA == "raw_text" ]]
		  then
			RAW_READ="TRUE"
		fi
	
	done < $INPUT
  else
	echo "NO INPUT FILE"
fi
echo "-------------------------------------------------------------------------"

rm adds.csv
