#!/bin/bash

URL_BASE="https://api.ethermine.org/"
URL_SUFF=
MINER="0xaacE5875639E50142D00DFe065e8883a94bda6c9"

ARG=$*

##
# Pool args
#  pool
#  blocks
#  network
#  server
#
# Miner args
#  dashboard
#  history
#  payouts
#  settings
#  statistics
#
# Worker args
#  workers
#  workHist
#  worker
#  workMon

if [ -n $ARG ]
then
	if [[ $ARG == "pool" ]]
	then
		URL_SUFF="poolStats"
	elif [[ $ARG == "blocks" ]]
	then
		URL_SUFF="blocks/history"
	elif [[ $ARG == "network" ]]
	then
		URL_SUFF="networkStats"
	elif [[ $ARG == "server" ]]
	then
		URL_SUFF="servers/history"
	elif [[ $ARG == "dashboard" ]]
	then
		URL_SUFF="miner/"$MINER"/dashboard"
	else
		echo "Options are pool, blocks, network, or server."
		echo date + "%T"
	fi
fi

if [[ -n $URL_SUFF ]]
then
	URL=$URL_BASE$URL_SUFF
	curl -s $URL > em.csv
fi
