#!/bin/bash

WORD=$*

URL_BASE='http://api.urbandictionary.com/v0/define?term='

URL=$URL_BASE$WORD
echo $WORD


curl -s $URL > ~/.scripts/udefine.json

jq '.list[0].definition' ~/.scripts/udefine.json > ~/.scripts/udefine.txt

echo "#var udefinition {" > ~/.scripts/udef.tin
cat ~/.scripts/udefine.txt >> ~/.scripts/udef.tin
echo "}" >> ~/.scripts/udef.tin
